mysite/jizhangben/urls.py
from django.conf.urls import  url
from . import  views

urlpatterns=[
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.details, name='details'),
    url(r'^(?P<question_id>[0-9]+)/result/$', views.results, name='result'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote')
        ]

mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^jizhangben/',include('jizhangben.urls',namespace='jizhangben')),
]

mysite/jizhangben/models.py
from django.db import models
from django.utils import  timezone
import datetime

# Create your models here.

class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')

    def __str__(self):
        return  self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now()-datetime.timedelta(days=1)

class Choice(models.Model):
    question=models.ForeignKey(Question)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)

mysite/jizhangben/views.py
from django.shortcuts import render,get_object_or_404
from  django.http import  HttpResponse
from  .models import  Question
from django.http import  Http404
from django.template import RequestContext,loader
# Create your views here.
def index(request):
    latest_question_list=Question.objects.order_by('-pub_date')[0:5]
    template=loader.get_template('jizhangben/index.html')

    context={
        'latest_question_list': latest_question_list,
    }
    return  render(request,'jizhangben/index.html',context)

def results(request,question_id):
    response="You're looking at the results of question %s."
    return  HttpResponse(response%question_id)

def details(request,question_id):
   question=get_object_or_404(Question,pk=question_id)
   return  render(request,"jizhangben/detail.html",{'question':question})

def vote(request,question_id):
    return HttpResponse("You're voting on question %s." % question_id)

mysite/jizhangben/templates/jizhangben/detail.html
<!DOCTYPE html>
<html lang="en">
<head>


</head>
<body>
<h1>{{question.question_text}}</h1>

<ul>
    {% for i in question.choice_set.all %}
        <li>{{i.choice_text}}</li>
    {% endfor %}



</ul>
</body>
</html>

mysite/jizhangben/templates/jizhangben/index.html
<!DOCTYPE html>
<html lang="en">

<body>

{% if latest_question_list %}
    <ul>

        {% for question in latest_question_list %}
        <li><a href="{% url 'jizhangben:details' question.id %}">{{question.question_text}}</a></li>
        {% endfor %}
    </ul>
{%  else %}
    <p>No polls are avaliable.</p>

{% endif %}

</body>
</html>